### ISSUE TITLE
No files matched your search criteria..

### ISSUE THREAD

**Issue by Heimdell** [jonascarpay/calligraphy#14]
`Calligraphy` refuses to see my sources.

```
$ ls
app  brick.cabal  dist-newstyle  docs  examples  package.yaml  src  stack.yaml  stack.yaml.lock  tests
$ cabal install --ghc-options=-fwrite-ide-info --overwrite-policy=always
...
$ calligraphy --output-png out.png
No files matched your search criteria..
```

How do I fix it?

**Comment by jonascarpay** [comment]
Strange, what does `find -name '*.hie'` output? It should list some `hie` files, like this:
```
$ find -name '*.hie'
./dist-newstyle/build/x86_64-linux/ghc-9.0.2/foo-0/build/Lib.hie
./dist-newstyle/build/x86_64-linux/ghc-9.0.2/foo-0/t/dep-test/build/dep-test/dep-test-tmp/Main.hie
```

**Comment by Heimdell** [comment]
I does indeed list all my modules like this:

```
./.stack-work/dist/x86_64-linux/Cabal-3.6.3.0/build/NameCategory.hie
```

**Comment by Heimdell** [comment]
Running
```
$ cabal build --ghc-options=-fwrite-ide-info --overwrite-policy=always
```
fixed the issue.

**Comment by Nisarg1112** [comment]
Hey, @Heimdell @jonascarpay  I'm also facing the same issue, I'm using stack to generate hie files(see below command).
` stack build --ghc-options=-fwrite-ide-info`

hie files are present in a module like this -

`/.stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/project/App.hie`

But if I do `calligraphy -p out.png` it says -
`No files matched your search criteria..`

Can you please help me how to resolve this issue?
