### ISSUE TITLE
GHCi does not work with calligraphy 0.1.5

### ISSUE THREAD

**Issue by kazu-yamamoto** [jonascarpay/calligraphy#31]
After installing calligraphy 0.1.5, I cannot calculate even `1+2` in `ghci`. 
This is because the version provides `Prelude`.
As workaround, I keep the command but removed the library of calligraphy 0.1.5.

**Comment by Kleidukos** [comment]
@jonascarpay understood!

**Comment by kazu-yamamoto** [comment]
The issue has been fixed.
Thank you for the quick fix!
