### ISSUE TITLE
How can I get relationships between modules only?

### ISSUE THREAD

**Issue by Kleidukos** [jonascarpay/calligraphy#36]
Context: I'm inheriting a legacy codebase and I would like to produce graphs with various levels of precision. To start, I want to determine the relationship between every module. Is this something that can be done with the current options?

**Comment by jonascarpay** [comment]
I think `--collapse-modules` should do what you're trying to do

**Comment by Kleidukos** [comment]
Perfect, it's exactly what I needed! Thanks a lot.
