### ISSUE TITLE
Ability to just show a module dependency tree

### ISSUE THREAD

**Issue by ocharles** [jonascarpay/calligraphy#4]
Hi, first of all - thank you for making this excellent tool!

Something I'd really like on big projects is to get the 10000ft picture by just looking at the module dependency graph. Right now modules are just clusters of nodes, so if we hide everything we'd naturally have nothing to see. It would be cool if modules themselves could be a node, and we could collapse everything down into just module nodes.

**Comment by jonascarpay** [comment]
I've been thinking about that too. I initially thought it'd be tricky to present it to the user in a sensible way, but I think there might be a good way around it. I'll take a stab at this later today.

**Comment by ocharles** [comment]
If I can suggest one potential option:

* Add an option to show modules as nodes in the graph, this would probably be off by default to avoid clutter.
* Add more `--collapse` flags to collapse everything into the module node. Maybe `--collapse` could be added to turn on all collapsing flags at once

Then the user can just `--show-module-nodes --collapse --no-cluster-modules`.

I'm not wed to this idea though - you know better than me!
