### ISSUE TITLE
Hide all non-top-level definitions

### ISSUE THREAD

**Issue by ocharles** [jonascarpay/calligraphy#8]
Hi, me again! I'd like to have a view that hides all local definitions, but retains top-level values even if they aren't exported. My reasoning is I'd like to see locally defined top-level functions that are only used once (as that suggests it might be simpler to just inline). Right now, seeing all `where` and `let`-bound values makes this quite difficult.

**Comment by jonascarpay** [comment]
Did you look at `--collapse-values`? If I understand correctly, that should do exactly what you're looking for.

**Comment by ocharles** [comment]
Oh, I had not - that's perfect. Thanks!
